//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _03Model.Models
{
    using System;
    using System.Collections.Generic;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    //System.ComponentModel底下的東西要另外Using
    public partial class tStudent
    {
        [DisplayName("學號")]
        [Required(ErrorMessage = "學號為必填")]//注入  //驗證有沒有填欄位
        [RegularExpression("[12][0-5][6-9][0-9]{3}", ErrorMessage = "學號格式錯誤")]  //正規表達式:[]裡都是或分隔，幾個[]就是幾碼；[12]為1或2；[0-5]為0到5；[0-9]{3}為{3}前面要出現3次
        public string fStuId { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名為必填")]        
        public string fName { get; set; }

        [DisplayName("E-Mail")]
        [Required(ErrorMessage = "電子郵件為必填")]
        [EmailAddress(ErrorMessage ="電子郵件格式錯誤")]
        public string fEmail { get; set; }

        [DisplayName("成績")]        
        [Range(0,100, ErrorMessage = "成績請填0~100")]  //驗證數值
        public Nullable<int> fScore { get; set; }   //可以不填的
    }
}
